import {Colors, EmbedBuilder} from "discord.js";

export function getGeneralErrorEmbed() {
    return new EmbedBuilder()
        .setDescription(`There was a genewaw ewwow teehee.`)
        .setColor(Colors.Red)
}

export function getGeneralEmbed() {
    return new EmbedBuilder()
        .setColor(Colors.Blurple)
        .setTimestamp()
        .setFooter({text: 'Generated by yummy wummy mummy'});
}
