name: Build, Push and Deploy a Docker Image

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build image
        working-directory: ./discord
        run: docker build -t registry.digitalocean.com/hitagi/yume:latest .
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/hitagi/yume:latest
