on:
  push:
    paths:
      - "discord/**"
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI Quotes

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - name: Install doctl
      #        uses: digitalocean/action-doctl@v2
      #        with:
      #          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #
      #      - name: Log in to DO Container Registry
      #        run: doctl registry login --expiry-seconds 600

      - name: Build, tag, and push the discord image to Amazon ECR
        id: build-discord-bot
        working-directory: ./discord
        env:
          REGISTRY: davonbarnette
          REPOSITORY: discord
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to DO 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker images
          echo "Pushing image to DO... $REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"
